require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'script/**/*'
    - 'app/channels/**/*'
    - 'app/jobs/**/*'
    - 'app/mailers/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
  RSpec:
    Patterns:
    - _spec.rb
    - "(?:^|/)spec/"

  RSpec/FactoryBot:
    Patterns:
    - spec/factories/**/*.rb

Documentation:
  Enabled: false
